development:
  adapter: postgresql
  encoding: unicode
  database: development
  pool: 2

production:
  adapter: postgresql
  encoding: unicode
  database: production
  pool: 5
  host: <%= ENV['DATABASE_URL'] %>
